from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict

PROJECT_ROOT: Path = Path(__file__).resolve().parent.parent
BIOMARKERS_PATH: Path = PROJECT_ROOT / "src" / "biomarkers.yaml"

UNMAPPED: str = "unmapped"

MIN_CHRONOLOGICAL_AGE: int = 18
MAX_CHRONOLOGICAL_AGE: int = 100
MIN_SLEEP_HOURS: float = 3.0
MAX_SLEEP_HOURS: float = 12.0
MAX_ALCOHOL_UNITS_PER_WEEK: float = 50.0
MAX_EXERCISE_MINUTES_PER_WEEK: int = 1000
STRESS_SCALE_MIN: int = 1
STRESS_SCALE_MAX: int = 10

LOW_SLEEP_HOURS: float = 6.0
HIGH_SLEEP_HOURS: float = 9.5
WEEKLY_EXERCISE_TARGET_MINUTES: int = 150
HEAVY_DRINKING_UNITS_PER_WEEK: float = 14.0
HIGH_STRESS_SCORE: int = 7
LOW_SUN_BIOMARKER: str = "vitamin_d"

AGE_MODEL_ID: str = "iitolstykh/mivolo_v2"
AGE_MODEL_REVISION: str = "53393526c220e34cdd7b722b36d22b6f9e5f4241"

FACE_CROP_SIZE: int = 224
FACE_CROP_MARGIN: float = 0.25
MIN_FACE_PIXELS: int = 60
MIN_MEAN_BRIGHTNESS: float = 30.0
MAX_MEAN_BRIGHTNESS: float = 225.0
HAAR_SCALE_FACTOR: float = 1.05
HAAR_MIN_NEIGHBORS: int = 4
HAAR_EYE_MIN_NEIGHBORS: int = 4
DETECTION_PAD_FRACTION: float = 0.2
# Blur threshold, measured after contrast is equalised so darker skin is not penalised.
CONTRAST_NORMALIZED_STD: float = 50.0
MIN_NORMALIZED_SHARPNESS: float = 9.6

MIN_PREDICTED_AGE: float = 1.0
MAX_PREDICTED_AGE: float = 100.0
# 80% error range by predicted age, measured on 30,000 UTKFace and AgeDB faces.
APPARENT_AGE_RANGE_BY_PREDICTION: tuple[tuple[float, float], ...] = (
    (30.0, 5.3),
    (40.0, 7.9),
    (float("inf"), 9.5),
)

MIN_PDF_TEXT_CHARS: int = 200
OCR_DPI: int = 300
MAX_LAB_PDF_PAGES: int = 20
EXTRACTION_RETRIES: int = 1

MAX_FACTORS: int = 5
MAX_RECOMMENDATIONS: int = 5

# Dose, medication-change and diagnosis patterns, including hedged ones, that fail a report.
UNSAFE_OUTPUT_PATTERNS: tuple[str, ...] = (
    r"\b(?:may|might|could|can)\s+(?:indicate|suggest|signal|mean|point\s+to)\b",
    r"\bsuggests?\b",
    r"\b(?:signs?|symptoms?)\s+of\b",
    r"\bconsistent\s+with\b",
    r"\bdeficien(?:cy|cies|t)\b",
    r"\b\d+(?:\.\d+)?\s*(?:mg|mcg|µg|ug|iu|milligrams?|micrograms?)\b(?!\s*/)",
    r"(?<!not )(?<!never )(?<!n't )\b(?:start|stop|increase|decrease|double|halve)\s+"
    r"(?:taking|your\s+(?:dose|medication))\b",
    r"(?<!not )(?<!that )\b(?:you|they)\s+"
    r"(?:have|are\s+suffering\s+from|were\s+diagnosed\s+with)\s+"
    r"(?:diabetes|prediabetes|hypothyroidism|hyperthyroidism|anemia|anaemia|cancer|"
    r"fatty\s+liver|heart\s+disease|kidney\s+disease)\b",
)

DISCLAIMER: str = (
    "This report is an educational wellness summary generated by a machine learning "
    "pipeline. It is not a medical device, not a diagnosis, and not a substitute for "
    "professional care. Nothing here should be used to start, stop, or change any "
    "medication or supplement. Discuss any concerns, and any laboratory result, with a "
    "qualified clinician."
)

ESCALATION_TEMPLATE: str = (
    "Your {display_name} result of {value} {unit} falls outside the range this tool is "
    "designed to comment on. Please share this result with a clinician promptly. No "
    "lifestyle guidance in this report is a substitute for that conversation."
)


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    llm_model: str = "qwen3:8b"
    # None keeps the model's own recommended sampling; Qwen repeats itself at temperature 0.
    llm_temperature: float | None = None
    llm_timeout_seconds: float = 600.0
    llm_max_tokens: int = 8192
    ollama_host: str = "http://localhost:11434"
    tesseract_cmd: str | None = None
    default_report_path: Path = PROJECT_ROOT / "report.pdf"
    torch_device: Literal["auto", "cpu", "cuda", "mps"] = "auto"


settings = Settings()
